In [4]:
from gooddata_pandas import GoodPandas
from gooddata_sdk import ObjId
import os

In [5]:
gdf = GoodPandas(
    host=os.environ["TIGER_ENDPOINT"],
    token=os.environ["TIGER_API_TOKEN"]
).data_frames(workspace_id="faa_custom")

In [6]:
indexed_df = gdf.indexed(
    index_by=dict(
        name=ObjId(id="nickname", type="label"),
    ),
    columns=dict(
        flight_count=ObjId(id="flight_count", type="metric"),
        destination_count=ObjId(id="destination_count", type="metric"),
        percentage_of_flights=ObjId(id="percentage_of_flights", type="metric"),
    ),
).sort_values("percentage_of_flights", ascending=False)

display(indexed_df)

                     flight_count  destination_count  percentage_of_flights
name
Southwest                 88751.0               63.0               0.257378
USAir                     37683.0               82.0               0.109281
American                  34577.0               89.0               0.100273
Northwest                 33580.0               88.0               0.097382
United                    32757.0               89.0               0.094995
Delta                     32130.0               97.0               0.093177
Continental Express       16074.0              126.0               0.046615
American Eagle            15869.0               77.0               0.046020
Atlantic Southeast        15769.0               60.0               0.045730
America West               9750.0               41.0               0.028275
Alaska                     8453.0               22.0               0.024514
Continental                7139.0               78.0               0.020703
Jetblue                    4842.0               32.0               0.014042
Comair                     4420.0              121.0               0.012818
ATA                        3033.0               25.0               0.008796

In [8]:
indexed_df = gdf.for_insight(insight_id="flights_by_carrier").sort_values("percentage_of_flights", ascending=False)

display(indexed_df)

                     flight_count  destination_count  percentage_of_flights
nickname
Southwest                 88751.0               63.0               0.257378
USAir                     37683.0               82.0               0.109281
American                  34577.0               89.0               0.100273
Northwest                 33580.0               88.0               0.097382
United                    32757.0               89.0               0.094995
Delta                     32130.0               97.0               0.093177
Continental Express       16074.0              126.0               0.046615
American Eagle            15869.0               77.0               0.046020
Atlantic Southeast        15769.0               60.0               0.045730
America West               9750.0               41.0               0.028275
Alaska                     8453.0               22.0               0.024514
Continental                7139.0               78.0               0.020703
Jetblue                    4842.0               32.0               0.014042
Comair                     4420.0              121.0               0.012818
ATA                        3033.0               25.0               0.008796